"""aios_kernel.persistence - SQLAlchemy ORM + Alembic migrations (T0032)."""
from aios_kernel.persistence.models import (
    ArtifactORM,
    Base,
    EvidenceORM,
    GoalORM,
    LongTermMemoryORM,
    PlanORM,
    TaskORM,
    TraceORM,
    VerifierRunORM,
    WorkerRunORM,
    WorkingMemoryORM,
    artifact_to_orm,
    envelope_json_of,
    evidence_to_orm,
    goal_to_orm,
    long_term_memory_to_orm,
    plan_to_orm,
    task_to_orm,
    trace_to_orm,
    working_memory_from_orm,
    working_memory_to_orm,
)
from aios_kernel.persistence.repository import (
    SqlAlchemyRepository,
    create_all,
    drop_all,
)

__all__ = [
    "Base",
    "GoalORM",
    "TaskORM",
    "PlanORM",
    "ArtifactORM",
    "EvidenceORM",
    "TraceORM",
    "WorkerRunORM",
    "VerifierRunORM",
    "WorkingMemoryORM",
    "LongTermMemoryORM",
    "goal_to_orm",
    "task_to_orm",
    "plan_to_orm",
    "artifact_to_orm",
    "evidence_to_orm",
    "trace_to_orm",
    "long_term_memory_to_orm",
    "working_memory_to_orm",
    "working_memory_from_orm",
    "envelope_json_of",
    "SqlAlchemyRepository",
    "create_all",
    "drop_all",
]
