@echo off
REM Auto-dispatch sovereignty-v:T11 to claude CLI
REM Generated by codex 01a11c30 · 2026-10-09T00:16+08:00

set ADAPTER_SPEC=D:\AIOS\_agent-hub\policy\adapter-spec.v1.md
set OUT_PATH=D:\AIOS\_agent-hub\policy\adapters\openclaw_runtime.py
set DONE_PATH=D:\AIOS\_agent-hub\reports\sovereignty-v\tasks\T11.done
set RUNTIME=openclaw
set TASK_ID=sovereignty-v:T11

echo [DISPATCH] %TASK_ID% for runtime %RUNTIME
echo [OUT] %OUT_PATH%
echo [DONE] %DONE_PATH%
echo.

REM Write prompt to file (avoid cmd line length limit)
set PROMPT_FILE=D:\AIOS\_agent-hub\reports\sovereignty-v\dispatch_T9_T12\prompt_openclaw.txt

REM Use claude CLI with the prompt as -p arg via file
claude -p "%PROMPT_FILE:~,-4%"

echo [DONE] %TASK_ID%
