@echo off
REM Register AIOS ModelPolicy Reconciler (Mode A: persistent Task Scheduler, 5-min interval)
REM v3 — uses Python for sha256 check (avoids PS module loading issues).
REM Generated by codex 01a11c30 (supervisor) — T7-deploy step.

setlocal
set RECON_DIR=D:\AIOS\_agent-hub\policy\reconciler
set POLICY=D:\AIOS\_agent-hub\policy\model-policy.v1.yaml
set MANIFEST=D:\AIOS\_agent-hub\policy\model-policy.v1.sha256
set TASK=AIOS_ModelPolicy_Reconciler

REM Step 1: single-instance guard
wmic process where "name='python.exe' and commandline like '%%reconciler.py%%'" get ProcessId 2>nul | findstr /R "[0-9]" >nul
if not errorlevel 1 (
  echo [SKIP] Reconciler already running.
  exit /b 0
)

REM Step 2: sanity
if not exist "%POLICY%" (
  echo [FATAL] policy file missing
  exit /b 1
)
if not exist "%MANIFEST%" (
  echo [FATAL] sha256 manifest missing
  exit /b 1
)

REM Step 3: sha256 verify via Python (deterministic + portable)
python "%RECON_DIR%\verify_sha256.py"
if errorlevel 1 (
  echo [FATAL] sha256 verify failed. Aborting registration.
  exit /b 2
)

REM Step 4: register schtasks
schtasks /Create /TN "%TASK%" /TR "python \"%RECON_DIR%\reconciler.py\" --policy \"%POLICY%\" --sha256-manifest \"%MANIFEST%\"" /SC MINUTE /MO 5 /F
if errorlevel 1 (
  echo [WARN] schtasks register failed; fallback to on-demand.
  start "" python "%RECON_DIR%\reconciler.py" --policy "%POLICY%"
  exit /b 1
) else (
  echo [OK] Reconciler registered: %TASK% every 5 min.
)

REM Step 5: one-shot run
python "%RECON_DIR%\reconciler.py" --policy "%POLICY%" --sha256-manifest "%MANIFEST%" --once

endlocal